site_name: Taskly Documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorials:
    - Python: tutorials/tutorial-python.md
    - JavaScript: tutorials/tutorial-js.md
    - cURL: tutorials/tutorial-curl.md
  - API Reference: api/index.md 
  - CLI: cli.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.keys


theme:
  name: material
  features:
  - content.code.copy
  - content.code.annotate
  - content.tabs

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  # Note: extra_css line can be added later for custom styles
