site_name: Taskly Documentation

theme:
  name: material
  features:
    - content.code.copy
  palette:
    scheme: default
    primary: indigo
    accent: indigo

  font: false
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.0/mermaid.min.js

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorials:
      - Python: tutorials/tutorial-python.md
      - JavaScript: tutorials/tutorial-js.md
      - cURL: tutorials/tutorial-curl.md
  - API Reference: api/index-api.md
  - CLI: cli.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - Release Notes: release-notes.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.progressbar
  - pymdownx.arithmatex
  - pymdownx.snippets


extra_css:
  - stylesheets/extra.css    # Custom table/code styling

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - content.code.copy      # Copy button on code blocks
    - content.code.annotate  # Code annotation support
    - content.tabs           # Tabs for multi-language/code example switches

validation:
  links:
    absolute_links: relative_to_docs # Enables /... links from docs root (MkDocs 1.6+)

# Optional: Make nice URLs on GitHub Pages
use_directory_urls: true

# Your docs folder may look like:
# docs/
#   index.md
#   quickstart.md
#   api/index.md
#   tutorials/tutorial-python.md
#   tutorials/tutorial-js.md
#   tutorials/tutorial-curl.md
#   cli.md
#   troubleshooting.md
#   contributing.md
#   release-notes.md
#   stylesheets/extra.css
